config/routes.rb
MHAText::Application.routes.draw do
  root :to => "pages#start"

  resources :text_sessions
  
  resources :reports

  post "key_strokes/create" 

  get "pages/start"
  post "pages/start" =>"pages#start_redirect"

  get "pages/write_text_1"
  post "pages/write_text_1" => "pages#write_text_1_save"

  get "pages/write_text_2"
  post "pages/write_text_2" => "pages#write_text_2_save"
  
  get "pages/finish"

end

app/views/pages/data.html.erb
<div class="block">
  <h2 class="title">KeyStroke Count</h2>
  <div class="content">
    <p><%= KeyStroke.count%></p>
  </div> <!-- content -->
</div><!-- block -->

app/views/pages/finish.html.erb
<div class="block">
  <h2 class="title">Texterfassung abgeschlossen</h2>
	<div class="content">
			<div class="group">
    		<h3> Vielen Dank für Ihre Teilnahme!</h3>
				<p>Ihre Texteingabe wurde gespeichert.</p>
				<hr/>
				<p><%= link_to "Neue Texterfassung starten", pages_start_path %></p>
			</div>
	</div>	
</div>

app/views/pages/start.html.erb
<div class="block">
  <h2 class="title">Willkommen zur Texterfassung</h2>
  <div class="content">
    <p>Auf der folgenden Seite finden Sie einen zufällig ausgewählten Text. Ihre Aufgabe ist es diesen so schnell wie möglich, fehlerfrei ab zu tippen. Sie haben dafür 5 Minuten Zeit, danach beendet sich die Eingabe automatisch.</p>
    <p>Abhänig von Ihrer Tippgeschwindigkeit werden Sie den Text nicht vollständig abschreiben können. Der Text ist so gewählt das Sie nur bei sehr hoher Tippgeschwindigkeit fertig werden.</p>
    <p> Sobald Sie bereit sind geben Sie bitte Ihre Probandennummer ein. Der Test startet direkt nach der Eingabe:</p>
    <%= form_tag pages_start_path, :method => :post, :class => "form" %>
    <div class="group">
      <%= label_tag :user_id, "Probandennummer", :class => "label" %>
      <%= text_field_tag :user_id, '' ,:class => "text_field" %>
    </div>
    <div class="group wat-cf">
      <%= button_tag "Test starten", :class => "button" %>
    </div>
  </div> <!-- content -->
</div><!-- block -->

app/views/pages/write_text_1.html.erb
<% content_for :header do %>
<% end %>
<div class="block">
  <div class="content">
    <div class="inner">
      <h2 class="title intended">Textvorlage</h2>
      <div id="countdown">
        Countdown
      </div>
      <span class="intended">Bitte schreiben Sie diesen Text möglicht schnell und fehlerfrei ab. Sie haben 5 Minuten für diese Aufgabe Zeit.</span>
      <p class="master"><%= @text_session.texts[@text_session.text_1] %></p>
     </div><!-- inner -->
  </div> <!-- content -->
</div><!-- block -->
<div class="block">
	<div class="content">
		<div class="inner">
		  <p>&nbsp;</p>
			<form id="input_form" class="form" action="<%= pages_write_text_1_path %>" method="post" accept-charset="utf-8">
				<div class="group">
				  
					<label for="input" class="label intended">Abschrift eingeben:</label>
					<textarea class="text_area intended" name="input" cols="80" rows="20" id="input"></textarea>
					<div class="description intended">Bitte geben Sie Ihre Abschrift hier ein und klicken Sie anschließend auf "Text fertiggestellt"</div>
				</div>
				<div class="group navform wat-cf">
				  <button class="button" type="submit">
					  <%= image_tag 'icons/tick.png' %>
					  Text fertiggestellt
				  </button>
        </div>	
				<input type="hidden" name="text_session_id" id="user_id" value="<%= @text_session.id %>"/>
			</form>
			<h3>Messages</h3>
			<p id="message"></p>
		</div>
	</div>	
</div>

app/views/pages/write_text_2.html.erb
<% content_for :header do %>
<% end %>
<div class="block">
  <div class="content">
    <div class="inner">
      <h2 class="title intended">Textvorlage</h2>
      <div id="countdown">
        Countdown
      </div>
      <span class="intended">Bitte schreiben Sie diesen Text möglichst schnell und fehlerfrei ab. Sie haben 5 Minuten für diese Aufgabe Zeit.</span>
      <p class="master"><%= @text_session.texts[@text_session.text_2] %></p>
     </div><!-- inner -->
  </div> <!-- content -->
</div><!-- block -->
<div class="block">
	<div class="content">
		<div class="inner">
			<form id="input_form" class="form" action="<%= pages_write_text_2_path %>" method="post" accept-charset="utf-8">
				<div class="group">
				  <p>&nbsp;</p>
					<label for="input" class="label intended">Abschrift eingeben:</label>
					<textarea class="text_area intended" name="input" cols="80" rows="20" id="input"></textarea>
					<div class="description intended">Bitte geben Sie Ihre Abschrift hier ein und klicken Sie anschließend auf "Text fertiggestellt"</div>
				</div>
				<div class="group navform wat-cf">
				  <button class="button" type="submit">
					  <%= image_tag 'icons/tick.png' %>
					  Text fertiggestellt
				  </button>
        </div>	
				<input type="hidden" name="text_session_id" id="user_id" value="<%= @text_session.id %>"/>
			</form>
			<h3>Messages</h3>
			<p id="message"></p>
		</div>
	</div>	
</div>