config/routes.rb
MHAText::Application.routes.draw do
  root :to => "pages#start"

  resources :text_sessions
  
  resources :reports

  post "key_strokes/create" 

  get "pages/start"
  post "pages/start" =>"pages#start_redirect"

  get "pages/write_text_1"
  post "pages/write_text_1" => "pages#write_text_1_save"

  get "pages/write_text_2"
  post "pages/write_text_2" => "pages#write_text_2_save"
  
  get "pages/finish"

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                                               :integer          not null, primary key
#  created_at                                       :datetime
#  updated_at                                       :datetime
#  levenshtein_distance_stressed                    :integer
#  levenshtein_distance_unstressed                  :integer
#  length_difference_stressed                       :integer
#  length_difference_unstressed                     :integer
#  text_session_id                                  :integer
#  average_time_distance_matrix_unstressed          :text
#  average_time_distance_stressed                   :float
#  average_time_distance_unstressed                 :float
#  average_time_distance_matrix_stressed            :text
#  count_differences_without_corrections_unstressed :integer
#  count_differences_without_corrections_stressed   :integer
#  correction_count_stressed                        :integer
#  correction_count_unstressed                      :integer
#

class Report < ActiveRecord::Base
  belongs_to :text_session
  validates :text_session, presence: true

  serialize :histogram_us, Array
  serialize :histogram_s, Array

  store :key_stroke_counts, accessors: [
    :backspace_count_unstressed, :backspace_count_stressed,
    :del_count_unstressed, :del_count_stressed,
    :space_count_unstressed, :space_count_stressed,
    :arrow_count_unstressed, :arrow_count_stressed,
    :letter_e_count_unstressed, :letter_e_count_stressed,
    :letter_n_count_unstressed, :letter_n_count_stressed,
    :letter_i_count_unstressed, :letter_i_count_stressed,
    :letter_s_count_unstressed, :letter_s_count_stressed,
    :letter_r_count_unstressed, :letter_r_count_stressed,
    :letter_a_count_unstressed, :letter_a_count_stressed,

    :pauses_unstressed, :pauses_stressed,
    :pause_time_unstressed, :pause_time_stressed,

    :backspace_time_unstressed, :backspace_time_stressed,
    :del_time_unstressed, :del_time_stressed,
    :space_time_unstressed, :space_time_stressed,
    :arrow_time_unstressed, :arrow_time_stressed,
    :letter_e_time_unstressed, :letter_e_time_stressed,
    :letter_n_time_unstressed, :letter_n_time_stressed,
    :letter_i_time_unstressed, :letter_i_time_stressed,
    :letter_s_time_unstressed, :letter_s_time_stressed,
    :letter_r_time_unstressed, :letter_r_time_stressed,
    :letter_a_time_unstressed, :letter_a_time_stressed,

    :average_p2r_time_unstressed, :average_p2r_time_stressed,
    :average_r2p_time_unstressed, :average_r2p_time_stressed,

    :inter_word_count_unstressed, :inter_word_count_stressed,
    :inter_word_fly_time_unstressed, :inter_word_fly_time_stressed,

    :capital_case_starting_letter_count_unstressed, :capital_case_starting_letter_count_stressed,
    :capital_case_starting_letter_p2r_unstressed, :capital_case_starting_letter_p2r_stressed,
    :capital_case_starting_letter_r2p_unstressed, :capital_case_starting_letter_r2p_stressed,
    :lower_case_starting_letter_count_unstressed, :lower_case_starting_letter_count_stressed,
    :lower_case_starting_letter_p2r_unstressed, :lower_case_starting_letter_p2r_stressed,
    :lower_case_starting_letter_r2p_unstressed, :lower_case_starting_letter_r2p_stressed,
    :in_word_letter_count_unstressed, :in_word_letter_count_stressed,
    :in_word_letter_p2r_unstressed, :in_word_letter_p2r_stressed,
    :in_word_letter_r2p_unstressed, :in_word_letter_r2p_stressed,

    :common_letter_p2r_unstressed, :common_letter_p2r_stressed,
    :common_letter_r2p_unstressed, :common_letter_r2p_stressed,
    :uncommon_letter_p2r_unstressed, :uncommon_letter_p2r_stressed,
    :uncommon_letter_r2p_unstressed, :uncommon_letter_r2p_stressed
  ]

  store :word_timing, accessors: [
    :common_word_count_unstressed, :common_word_count_stressed,
    :common_word_p2r_unstressed, :common_word_p2r_stressed,
    :uncommon_word_count_unstressed, :uncommon_word_count_stressed,
    :uncommon_word_p2r_unstressed, :uncommon_word_p2r_stressed,
  ]

  serialize :ngram_data, Hash

  def self.build_from_text_session(text_session)
    report = Report.new
    report.text_session = text_session

    report
  end

  def group
    return "group1" if self.text_session.user_id.include?"G1"
    return "group2" if self.text_session.user_id.include?"G2"
    return "group4" if self.text_session.user_id.include?"G4"
  end


  def levenshtein_measure
    self.levenshtein_distance_unstressed - self.levenshtein_distance_stressed
  end

  def self.generate_csv(options = {})
    text_session_column_names = %w[user_id]
    report_column_names = %w[key_stroke_count_unstressed key_stroke_count_stressed
      levenshtein_distance_stressed levenshtein_distance_unstressed
      correction_count_stressed correction_count_unstressed]

    # Feature Count X
    report_key_stroke_counts_names = %w[
      backspace_count_stressed backspace_count_unstressed
      del_count_stressed del_count_unstressed
      space_count_stressed space_count_unstressed
      arrow_count_stressed arrow_count_unstressed ]

    # Feature Single Letter Average X
    report_key_stroke_counts_names += %w[
      letter_e_time_unstressed letter_e_time_stressed
      letter_n_time_unstressed letter_n_time_stressed
      letter_i_time_unstressed letter_i_time_stressed
      letter_s_time_unstressed letter_s_time_stressed
      letter_r_time_unstressed letter_r_time_stressed
      letter_a_time_unstressed letter_a_time_stressed
      backspace_time_unstressed backspace_time_stressed
      del_time_unstressed del_time_stressed
      space_time_unstressed space_time_stressed
      arrow_time_unstressed arrow_time_stressed ]

    # Feature Average P2R Time, Average R2P Time
    report_key_stroke_counts_names += %w[
      average_p2r_time_unstressed average_p2r_time_stressed
      average_r2p_time_unstressed average_r2p_time_stressed
    ]

    # Feature Inter Word Flytime
    report_key_stroke_counts_names += %w[
      inter_word_fly_time_unstressed inter_word_fly_time_stressed ]

    # Feature Common Letter Average, Uncommon Letter Average
    report_key_stroke_counts_names += %w[
      common_letter_p2r_unstressed common_letter_p2r_stressed
      common_letter_r2p_unstressed common_letter_r2p_stressed
      uncommon_letter_p2r_unstressed uncommon_letter_p2r_stressed
      uncommon_letter_r2p_unstressed uncommon_letter_r2p_stressed]

    # Feature Capital Word Starting Letter, Non-Capital Word Starting Letter
    # Non Starting Letter
    report_key_stroke_counts_names += %w[
      capital_case_starting_letter_p2r_stressed capital_case_starting_letter_p2r_unstressed
      capital_case_starting_letter_r2p_stressed capital_case_starting_letter_r2p_unstressed
      lower_case_starting_letter_p2r_stressed lower_case_starting_letter_p2r_unstressed
      lower_case_starting_letter_r2p_stressed lower_case_starting_letter_r2p_unstressed
      in_word_letter_p2r_stressed in_word_letter_p2r_unstressed
      in_word_letter_r2p_stressed in_word_letter_r2p_unstressed ]


    # Feature Common Words, Uncommon Words
    report_word_timing_names = %w[
      common_word_p2r_unstressed common_word_p2r_stressed
      common_word_r2p_unstressed common_word_r2p_stressed
      uncommon_word_p2r_unstressed uncommon_word_p2r_stressed
      uncommon_word_r2p_unstressed uncommon_word_r2p_stressed]

    report_ngrams = []

    (TextSession.common_bi_grams + TextSession.common_tri_grams).each do |ngram|
        report_ngrams << ["ngram_#{ngram}_count_unstressed", "ngram_#{ngram}_count_stressed",
        "ngram_#{ngram}_p2r_unstressed", "ngram_#{ngram}_p2r_stressed",
        "ngram_#{ngram}_r2p_unstressed", "ngram_#{ngram}_r2p_stressed" ]
    end

    report_ngrams.flatten!
    report_ngrams += %w[
      common_digram_p2r_stressed common_digram_p2r_unstressed
      common_digram_r2p_stressed common_digram_r2p_unstressed
      common_inter_digram_p2r_stressed common_inter_digram_p2r_unstressed
      common_inter_digram_r2p_stressed common_inter_digram_r2p_unstressed
      common_intra_digram_p2r_stressed common_intra_digram_p2r_unstressed
      common_intra_digram_r2p_stressed common_intra_digram_r2p_unstressed

      common_digram_p2r_1_stressed common_digram_p2r_1_unstressed
      common_inter_digram_p2r_1_stressed common_inter_digram_p2r_1_unstressed
      common_intra_digram_p2r_1_stressed common_intra_digram_p2r_1_unstressed

      uncommon_digram_p2r_stressed uncommon_digram_p2r_unstressed
      uncommon_digram_r2p_stressed uncommon_digram_r2p_unstressed
      uncommon_inter_digram_p2r_stressed uncommon_inter_digram_p2r_unstressed
      uncommon_inter_digram_r2p_stressed uncommon_inter_digram_r2p_unstressed
      uncommon_intra_digram_p2r_stressed uncommon_intra_digram_p2r_unstressed
      uncommon_intra_digram_r2p_stressed uncommon_intra_digram_r2p_unstressed

      double_letter_digram_p2r_stressed double_letter_digram_p2r_unstressed
      double_letter_digram_r2p_stressed double_letter_digram_r2p_unstressed
    ]

    report_ngrams += %w[
      common_tri_grams_p2r_stressed common_tri_grams_p2r_unstressed
      common_tri_grams_r2p_stressed common_tri_grams_r2p_unstressed
      uncommon_tri_grams_p2r_stressed uncommon_tri_grams_p2r_unstressed
      uncommon_tri_grams_r2p_stressed uncommon_tri_grams_r2p_unstressed
    ]

    CSV.generate(options) do |csv|
      csv << text_session_column_names + ["text_order"] + report_column_names +
        report_key_stroke_counts_names + report_word_timing_names + report_ngrams
      all.each do |report|
        csv << report.text_session.attributes.values_at(*text_session_column_names) +
          [report.text_session.text_order] +
          report.attributes.values_at(*report_column_names).map { |field| field.to_s.tr('.',',') } +
          report.key_stroke_counts.values_at(*report_key_stroke_counts_names.map(&:to_sym)).map { |field| field.to_s.tr('.',',') } +

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def show

  end

  def index
    @reports = Report.joins(:text_session).where("key_stroke_counts IS NOT NULL").order("text_sessions.user_id desc")
    respond_to do |format|
      format.html
      format.csv { send_data @reports.generate_csv }
    end
  end

  def show
    @report = Report.find_by_text_session_id(TextSession.find(params[:id]))

    if @report.present?
      @matrix = @report.calculate_average_time_distance_matrix(:unstressed)
      @list_unstressed = @report.calculate_time_distance_list(:unstressed)
      @list_stressed = @report.calculate_time_distance_list(:stressed)
      @keys = @report.key_press_combinations
      @strokes = @report.accrued_key_strokes_with_counts
    else
      redirect_to reports_path
    end
  end
end

app/helpers/report_helper.rb
module ReportHelper
  def to_letter(number)
    KeyStroke.keymap.invert[number.to_s]
  end
  
  def to_nubmer(char)
    KeyStroke.keymap[char.to_s]
  end
  
  def encode_chart_data(keys, list_unstressed, list_stressed)
    labels = []
    dvu = []
    dvs = []
    
    keys.each do |key|
       unless list_unstressed[key].present? && list_unstressed[key][:count] > 2 && 
              list_stressed[key].present? && list_stressed[key][:count] > 2
         next
      end
      
      labels << key
      dvu << ("%.2f" % list_unstressed[key][:average]).to_f
      dvs << ("%.2f" % list_stressed[key][:average]).to_f
    end
    
    "data-labels=#{labels.to_json} data-dvu=#{dvu.to_json} data-dvs=#{dvs.to_json}"
  end
end

app/views/reports/index.html.erb
<div class="block">
	<div class="content">
		<h2 class="title">Texterstellung - Auswertung</h2>

		<div class="inner">
          <p>Download as <%= link_to "CSV", reports_path(format: "csv") %></p>
          <table>
            <thead>
              <tr>
                <th>Probanden Code</th>
                <th>Text Order</th>
                <th># u</th>
                <th># s</th>
                <th># corr u</th>
                <th># corr s</th>
                <th># corr u - s</th>
                <th># LS u</th>
                <th># LS s</th>
                <th># LS u - s</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @reports.sort.each do |report| %>
                <tr class="<%= cycle('odd','even') + " " + report.group %>">
                    <td><%= report.text_session.user_id %></td>
                    <td><%= report.text_session.text_order %></th>
                    <td><%= report.key_stroke_count_unstressed %></td>
                    <td><%= report.key_stroke_count_stressed %></td>
                    <td><%= report.correction_count_unstressed %></td>
                    <td><%= report.correction_count_stressed %></td>
                    <% diff = report.correction_count_unstressed - report.correction_count_stressed -%>
                    <td <%=  diff < 0 ? "class=red" : "class=green" %>><%= number_with_precision( diff,:precision => 0) %></td>
                    <td><%= report.levenshtein_distance_unstressed %></td>
                    <td><%= report.levenshtein_distance_stressed %></td>
                    <td <%= report.levenshtein_measure < 0 ? "class=red" : "class=green" %>><%= number_with_precision( report.levenshtein_measure,:precision => 0) %></td>
                    <td><%= link_to "Weitere Reports", report_path(report.text_session.id)%></td>
                    <td><%= link_to "Text Session", text_session_path(report.text_session.id)%></td>
                </tr>
              <% end -%>
            </tbody>
          </table>
		</div> <!-- inner -->
</div> <!-- block -->

app/views/reports/show.html.erb
<div class="block">
    <div class="content">
        <h2 class="title">Texterstellung - Auswertung</h2>
        <div class="inner">
            <p><%= link_to "Übersicht", reports_path %></p>
            <p>
                Probanden Code = <%= @report.text_session.user_id %>
            </p>
            <h2>Time Difference List - Unstressed/Stressed</h2>
            <table class="list">
                <thead>
                    <tr>
                        <th>Kombination</th>
                        <th># u</th>
                        <th># s</th>
                        <th>Ø u</th>
                        <th>Ø u</th>
                    </tr>
                </thead>
                <tbody>
                    <% @keys.each do |element| %>
                    <% unless @list_unstressed[element].present? && @list_unstressed[element][:count] > 2 && 
                          @list_stressed[element].present? && @list_stressed[element][:count] > 2 
                          next
                      end
                    %>
                    <tr>
                        
                        <td><%= element.split(",")[0] %> zu <%= element.split(",")[1] %></td>
                        <td><%= @list_unstressed[element].present? ? @list_unstressed[element][:count] : "-"%></td>
                        <td><%= @list_stressed[element].present? ? @list_stressed[element][:count] : "-" %></td>
                        <td><%= @list_unstressed[element].present? ? number_with_precision(@list_unstressed[element][:average], :precision => 2)   : "-"  %></td>
                        <td><%= @list_stressed[element].present? ? number_with_precision(@list_stressed[element][:average], :precision => 2) : "-"  %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <table class="list">
                <thead>
                    <tr>
                        <th>Taste</th>
                        <th># u</th>
                        <th># s</th>
                    </tr>
                </thead>
                <tbody>
                    <% @strokes.each do |stroke| %>
                    <tr>
                        <td><%= stroke[0]%></td>
                        <td><%= stroke[1][:unstressed]%></td>
                        <td><%= stroke[1][:stressed]%></td>
                        <td <%= stroke[1][:unstressed] - stroke[1][:stressed] < 0 ? "class=red" : "class=green" %>>
                            <%= stroke[1][:unstressed] - stroke[1][:stressed] %>
                        </td>
                    </tr>
                    <% end -%>
                </tbody>
            </table>           
            <div id="chart" <%= encode_chart_data(@keys,@list_unstressed,@list_stressed) %> >
            </div>
            <div class="clear">&nbsp;</div>
            <h2>Time Differnece Matrix</h2>
            <table>
                <tbody>
                    <tr>
                        <td class="first"></td>
                        <% @report.accrued_key_strokes(:unstressed).each do |key| %> <td><%= key %></td>
                        <% end %>
                    </tr>
                    <% @report.accrued_key_strokes(:unstressed).each do |row_key| %>
                    <tr>
                        <td class="first"><%= row_key %></td>
                        <% @report.accrued_key_strokes(:unstressed).each do |column_key| %>
                        <% if @matrix[row_key][column_key].present? %> <td class="value"> <%= @matrix[row_key][column_key].count %> -
                            <%= number_with_precision(@matrix[row_key][column_key].sum.to_f / @matrix[row_key][column_key].count, :precision => 0) %> </td>
                        <% else %> 
                            <td>0</td>
                        <% end -%>
                        <% end -%>
                    </tr>
                    <% end -%>
                </tbody>
            </table>
        </div>
        <!-- inner -->
    </div>
    <!-- content -->
</div>
<!-- block -->