config/routes.rb
MHAText::Application.routes.draw do
  root :to => "pages#start"

  resources :text_sessions
  
  resources :reports

  post "key_strokes/create" 

  get "pages/start"
  post "pages/start" =>"pages#start_redirect"

  get "pages/write_text_1"
  post "pages/write_text_1" => "pages#write_text_1_save"

  get "pages/write_text_2"
  post "pages/write_text_2" => "pages#write_text_2_save"
  
  get "pages/finish"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MHA - Textanalyse</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'https://www.google.com/jsapi' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <%= yield :header %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">MHA - Textanalyse</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><%= link_to "Start", root_path %> </li>
          <li><%= link_to "Reports", reports_path %> </li>
          <li><%= link_to "Text Sessions", text_sessions_path %></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/box.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MHA - Textanalyse</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <%= yield :header %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">MHA - Textanalyse</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="box">
        <%= yield %>
        <div id="footer">
          <div class="block">
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/text_strokes.erb
<div class="block">
	<div class="content">
		<h2 class="title">Watcher - Übersicht</h2>
		<div class="inner">
				<div class="group">
				  <h3>Der finale Texte</h3>
				  <p><%= @text.finalText %></p>
				  <h3>Die Tastendrücke</h3>
          <table>
            <tr>
              <th>Type</th>
              <th>Tasten Code</th>
              <th>Zeitpunkt</th>
              <th>Modifikator</th>
          </tr>
          <% @strokes.each do |stroke| %>
            <tr>
              <td><%= stroke.type %></td>
              <td><%= stroke.strokedKey %></td>
              <td><%= "#{stroke.timeStamp.sec},#{stroke.timeStamp.usec}" %></td>
              <td><%= if stroke.altKey 
                        "alt " 
                      end
                      if stroke.shiftKey 
                        "shift "
                      end
                      if stroke.ctrlKey 
                        "ctrl"
                      end %></td>
            </tr>
          <% end %>
          </table>
				</div>
			<h3>Messages</h3>
			<p id="message"></p>
		</div>
	</div>	
</div>

app/views/layouts/texts.erb
<div class="block">
	<div class="content">
		<h2 class="title">Watcher - Übersicht</h2>
		<div class="inner">
				<div class="group">
          <table>
            <tr>
              <th>User Id</th>
              <th>Textanfang</th>
              <th>Details</th>
              <th>Zeitpunkt</th>
          </tr>
          <% @texts.each do |text| %>
            <tr>
              <td><%= text.userId %></td>
              <td><%= text.finalText[0..120] %></td>
              <td><a href="<%= "/text/#{text.id}" %>">anzeigen</a></td>
              <td><%= text.createDate %></td>
            </tr>
          <% end %>
          </table>
	</div>
	<h3>Messages</h3>
	<p id="message"></p>
	</div>
	</div>	
</div>